site_name: Game Design Document (GDD) - Cozy Neko World
site_url: https://Lility91.github.io/MKDocs_GDD_Cozy_Neko_World/
use_directory_urls: false

theme:
  name: mkdocs
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: indigo
      accent: indigo
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
  hljs_languages:
    - python
    - javascript
    - html
    - css
    - bash
    - yaml
    - json
  color_mode: auto
  user_color_mode_toggle: true

extra:
    base: /MKDocs_GDD_Cozy_Neko_World/

nav:
  - GDD: index.md
  - Anexos:
      - Extra! Extra! Nova Cara na Cidade: anexos/Extra_Extra_Nova_Cara_Na_Cidade.md
 # - Tutorial mkdocs: other/tut.md
 # - Checklist Acesso e Update MkDots + GitHub Pages: other/checklist.md

markdown_extensions:
  - tables
  - admonition
  - codehilite
  - footnotes


extra_css:
  - css/style.css
