site_name: Game Design Document (GDD) - Cozy Neko World
site_url: https://Lility91.github.io/MKDocs_GDD_Cozy_Neko_World/
use_directory_urls: false

theme: 
  name: mkdocs
  hljs_languages:
    - python
    - javascript
    - html
    - css
    - bash
    - yaml
    - json
  color_mode: auto
  user_color_mode_toggle: true

nav:
  - Home: index.md
  - Tutorial mkdocs: other/tut.md
  - Checklist Acesso e Update MkDots + GitHub Pages: other/checklist.md

markdown_extensions:
  - tables

extra_css:
  - css/style.css
