site_name: Game Design Document (GDD) - Cozy Neko World
site_url: https://Lility91.github.io/MKDocs_GDD_Cozy_Neko_World/
use_directory_urls: false

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: indigo
      accent: indigo
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
  hljs_languages:
    - python
    - javascript
    - html
    - css
    - bash
    - yaml
    - json

nav:
  - GDD: index.md
 # - Tutorial mkdocs: other/tut.md
 # - Checklist Acesso e Update MkDots + GitHub Pages: other/checklist.md

markdown_extensions:
  - tables

extra_css:
  - css/style.css
